version: '2'
services:
  springbootapp:
    image: springbootapp:latest
    container_name: springbootapp
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://productdb:3306/springBatchDocker?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 4446:4446

  mariadb:
    image: mariadb:latest
    container_name: productdb
    volumes:
      - /Users/user/Documents/docker/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springBatchDocker
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
